#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------

url: https://flink.apache.org

DOCS_BASE_URL: https://ci.apache.org/projects/flink/

FLINK_VERSION_STABLE: 1.7.2
FLINK_VERSION_HADOOP_2_STABLE: 1.7.2
FLINK_VERSION_STABLE_SHORT: 1.7

FLINK_VERSION_LATEST: 1.8-SNAPSHOT
FLINK_VERSION_LATEST_SHORT: 1.8

FLINK_ISSUES_URL: https://issues.apache.org/jira/browse/FLINK
FLINK_GITHUB_URL: https://github.com/apache/flink
FLINK_CONTRIBUTORS_URL: https://cwiki.apache.org/confluence/display/FLINK/List+of+contributors
FLINK_GITHUB_REPO_NAME: flink

optional_components:
  -
    name: "Avro"
    category: "SQL Formats"
    scala_dependent: false
    versions:
      -
        version: "1.7.2"
        id: 172-sql-format-avro
        url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-avro/1.7.2/flink-avro-1.7.2.jar
        asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-avro/1.7.2/flink-avro-1.7.2.jar.asc
        sha_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-avro/1.7.2/flink-avro-1.7.2.jar.sha1
  -
    name: "Json"
    category: "SQL Formats"
    scala_dependent: false
    versions:
      -
        version: "1.7.2"
        id: 172-sql-format-json
        url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-json/1.7.2/flink-json-1.7.2.jar
        asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-json/1.7.2/flink-json-1.7.2.jar.asc
        sha_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-json/1.7.2/flink-json-1.7.2.jar.sha1

# Example for scala dependent component:
#  -
#    name: "Prometheus MetricReporter"
#    category: "Reporters"
#    scala_dependent: true
#    versions:
#      -
#        version: "1.7.1"
#        scala_211:
#          id: 171-prometheus-211
#          url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar
#          asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.asc
#          sha_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.sha1
#        scala_212:
#          id: 171-prometheus-212
#          url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar
#          asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.asc
#          md1_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.sha1
#      -
#        version: "1.6.1"
#        scala_211:
#          id: 171-prometheus-211
#          url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar
#          asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.asc
#          sha_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.sha1
#        scala_212:
#          id: 171-prometheus-212
#          url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar
#          asc_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.asc
#          md1_url: https://repository.apache.org/content/groups/public/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.sha1

source_releases:
  -
      name: "Apache Flink 1.7.2"
      id: "172-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-src.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-src.tgz.asc"
      sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-src.tgz.sha512"
  -
      name: "Apache Flink 1.6.3"
      id: "163-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-src.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-src.tgz.asc"
      sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-src.tgz.sha512"
  -
      name: "Apache Flink 1.5.6"
      id: "156-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-src.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-src.tgz.asc"
      sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-src.tgz.sha512"
  -
      name: "Apache Flink-shaded 6.0"
      id: "s60-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-shaded-6.0/flink-shaded-6.0-src.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-shaded-6.0/flink-shaded-6.0-src.tgz.asc"
      sha512_url: "https://www.apache.org/dist/flink/flink-shaded-6.0/flink-shaded-6.0-src.tgz.sha512"


stable_releases:
  -
      name: "Apache Flink 1.7.2 only"
      scala_211:
          id: "172-download-hadoopfree_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.11.tgz.sha512"
      scala_212:
          id: "172-download-hadoopfree_212"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.12.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.12.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-scala_2.12.tgz.sha512"
  -
      name: "Apache Flink 1.7.2 with Hadoop® 2.8"
      scala_211:
          id: "172-download-hadoop28_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.11.tgz.sha512"
      scala_212:
          id: "172-download-hadoop28_212"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.12.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.12.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop28-scala_2.12.tgz.sha512"
  -
      name: "Apache Flink 1.7.2 with Hadoop® 2.7"
      scala_211:
          id: "172-download-hadoop27_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.11.tgz.sha512"
      scala_212:
          id: "172-download-hadoop27_212"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.12.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.12.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.12.tgz.sha512"
  -
      name: "Apache Flink 1.7.2 with Hadoop® 2.6"
      scala_211:
          id: "172-download-hadoop26_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.11.tgz.sha512"
      scala_212:
          id: "172-download-hadoop26_212"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.12.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.12.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop26-scala_2.12.tgz.sha512"
  -
      name: "Apache Flink 1.7.2 with Hadoop® 2.4"
      scala_211:
          id: "172-download-hadoop24_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop24-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop24-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop24-scala_2.11.tgz.sha512"
      scala_212:
          id: "172-download-hadoop24_212"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.7.2/flink-1.7.2-bin-hadoop24-scala_2.12.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop24-scala_2.12.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.7.2/flink-1.7.0-bin-hadoop24-scala_2.12.tgz.sha512"
  -
      name: "Apache Flink 1.6.3 only"
      scala_211:
          id: "163-download-hadoopfree_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-bin-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.6.3 with Hadoop® 2.8"
      scala_211:
          id: "163-download-hadoop28_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-bin-hadoop28-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop28-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop28-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.6.3 with Hadoop® 2.7"
      scala_211:
          id: "163-download-hadoop27_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-bin-hadoop27-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop27-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop27-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.6.3 with Hadoop® 2.6"
      scala_211:
          id: "163-download-hadoop26_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-bin-hadoop26-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop26-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop26-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.6.3 with Hadoop® 2.4"
      scala_211:
          id: "163-download-hadoop24_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.6.3/flink-1.6.3-bin-hadoop24-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop24-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.6.3/flink-1.6.3-bin-hadoop24-scala_2.11.tgz.sha512"
  -
      name: "Apache 1.5.6 Flink only"
      scala_211:
          id: "156-download-hadoopfree_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-bin-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.5.6 with Hadoop® 2.8"
      scala_211:
          id: "156-download-hadoop28_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-bin-hadoop28-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop28-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop28-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.5.6 with Hadoop® 2.7"
      scala_211:
          id: "156-download-hadoop27_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-bin-hadoop27-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop27-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop27-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.5.6 with Hadoop® 2.6"
      scala_211:
          id: "156-download-hadoop26_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-bin-hadoop26-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop26-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop26-scala_2.11.tgz.sha512"
  -
      name: "Flink 1.5.6 with Hadoop® 2.4"
      scala_211:
          id: "156-download-hadoop24_211"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.5.6/flink-1.5.6-bin-hadoop24-scala_2.11.tgz"
          asc_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop24-scala_2.11.tgz.asc"
          sha512_url: "https://www.apache.org/dist/flink/flink-1.5.6/flink-1.5.6-bin-hadoop24-scala_2.11.tgz.sha512"

FLINK_DOWNLOAD_URL_HADOOP_2_LATEST: https://s3.amazonaws.com/flink-nightly/flink-1.8-SNAPSHOT-bin-hadoop2.tgz

# Version numbers used in the text for stable and snapshot versions,
# e.g. "Documentation for {{ site.stable }".
stable: "1.7"
snapshot: "1.8"

docs-stable: "https://ci.apache.org/projects/flink/flink-docs-release-1.7"
docs-snapshot: "https://ci.apache.org/projects/flink/flink-docs-master"

# Used by the gh_link plugin
jira: "https://issues.apache.org/jira/browse/FLINK"
stackoverflow: "https://stackoverflow.com/search?q=flink"
twitter: "https://twitter.com/apacheflink"
github: "https://github.com/apache/flink"
wiki: "https://cwiki.apache.org/confluence/display/FLINK/Apache+Flink+Home"

twitter-handle: "ApacheFlink"

#baseurl: /incubator-flink-website

#------------------------------------------------------------------------------
# BUILD CONFIG
#------------------------------------------------------------------------------
# These variables configure the jekyll build (./build_docs.sh). You don't need
# to change anything here.
#------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: plain

markdown: KramdownPygments
highlighter: pygments

# The all languages used
languages: ['en', 'zh']

kramdown:
    toc_levels: 1..3
    input: GFM
    hard_wrap: false

redcarpet:
  # https://help.github.com/articles/github-flavored-markdown
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

exclude: [docker, flink-src-repo]

gems: ['jekyll-multiple-languages', 'jekyll-paginate']

host: 0.0.0.0

timezone: CET

# News Posts
paginate: 10
paginate_path: "blog/page:num"
