#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------

url: http://flink.apache.org

DOCS_BASE_URL: http://ci.apache.org/projects/flink/

FLINK_VERSION_STABLE: 1.4.1
FLINK_VERSION_HADOOP_2_STABLE: 1.4.1
FLINK_VERSION_STABLE_SHORT: 1.4

FLINK_VERSION_LATEST: 1.5-SNAPSHOT
FLINK_VERSION_LATEST_SHORT: 1.5

FLINK_ISSUES_URL: https://issues.apache.org/jira/browse/FLINK
FLINK_GITHUB_URL: https://github.com/apache/flink
FLINK_CONTRIBUTORS_URL: https://cwiki.apache.org/confluence/display/FLINK/List+of+contributors
FLINK_GITHUB_REPO_NAME: flink

FLINK_DOWNLOAD_URL_SOURCE: http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-src.tgz
FLINK_DOWNLOAD_URL_SOURCE_ASC: https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-src.tgz.asc
FLINK_DOWNLOAD_URL_SOURCE_MD5: https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-src.tgz.md5

stable_releases:
  -
      name: "Without bundled Hadoop®"
      id: "download-hadoopfree_211"
      url: "http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-bin-scala_2.11.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-scala_2.11.tgz.asc"
      md5_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-scala_2.11.tgz.md5"
  -
      name: "Hadoop® 2.8"
      id: "download-hadoop28_211"
      url: "http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-bin-hadoop28-scala_2.11.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop28-scala_2.11.tgz.asc"
      md5_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop28-scala_2.11.tgz.md5"
  -
      name: "Hadoop® 2.7"
      id: "download-hadoop27_211"
      url: "http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-bin-hadoop27-scala_2.11.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop27-scala_2.11.tgz.asc"
      md5_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop27-scala_2.11.tgz.md5"
  -
      name: "Hadoop® 2.6"
      id: "download-hadoop26_211"
      url: "http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-bin-hadoop26-scala_2.11.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop26-scala_2.11.tgz.asc"
      md5_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop26-scala_2.11.tgz.md5"
  -
      name: "Hadoop® 2.4"
      id: "download-hadoop24_211"
      url: "http://www.apache.org/dyn/closer.lua/flink/flink-1.4.1/flink-1.4.1-bin-hadoop24-scala_2.11.tgz"
      asc_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop24-scala_2.11.tgz.asc"
      md5_url: "https://www.apache.org/dist/flink/flink-1.4.1/flink-1.4.1-bin-hadoop24-scala_2.11.tgz.md5"

FLINK_DOWNLOAD_URL_HADOOP_2_LATEST: https://s3.amazonaws.com/flink-nightly/flink-1.5-SNAPSHOT-bin-hadoop2.tgz

# Version numbers used in the text for stable and snapshot versions,
# e.g. "Documentation for {{ site.stable }".
stable: "1.4"
snapshot: "1.5"

docs-stable: "http://ci.apache.org/projects/flink/flink-docs-release-1.4"
docs-snapshot: "http://ci.apache.org/projects/flink/flink-docs-master"

# Used by the gh_link plugin
jira: "https://issues.apache.org/jira/browse/FLINK"
stackoverflow: "http://stackoverflow.com/search?q=flink"
twitter: "https://twitter.com/apacheflink"
github: "https://github.com/apache/flink"
wiki: "https://cwiki.apache.org/confluence/display/FLINK/Apache+Flink+Home"

twitter-handle: "ApacheFlink"

#baseurl: /incubator-flink-website

#------------------------------------------------------------------------------
# BUILD CONFIG
#------------------------------------------------------------------------------
# These variables configure the jekyll build (./build_docs.sh). You don't need
# to change anything here.
#------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: plain

markdown: KramdownPygments
highlighter: pygments

kramdown:
    toc_levels: 1..3
    input: GFM
    hard_wrap: false

redcarpet:
  # https://help.github.com/articles/github-flavored-markdown
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

exclude: [docker, flink-src-repo]

gems: [jekyll-paginate]

host: 0.0.0.0

timezone: CET

# News Posts
paginate: 10
paginate_path: "blog/page:num"
