#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------

url: https://flink.apache.org

DOCS_BASE_URL: https://ci.apache.org/projects/flink/

FLINK_VERSION_STABLE: 1.13.0
FLINK_VERSION_STABLE_SHORT: "1.13"

FLINK_ISSUES_URL: https://issues.apache.org/jira/browse/FLINK
FLINK_GITHUB_URL: https://github.com/apache/flink
FLINK_CONTRIBUTORS_URL: https://cwiki.apache.org/confluence/display/FLINK/List+of+contributors
FLINK_GITHUB_REPO_NAME: flink

FLINK_STATEFUN_VERSION_STABLE: 3.0.0
FLINK_STATEFUN_STABLE_SHORT: "3.0"

FLINK_STATEFUN_GITHUB_URL: https://github.com/apache/flink-statefun
FLINK_STATEFUN_GITHUB_REPO_NAME: flink-statefun

# Example for scala dependent component:
#  -
#    name: "Prometheus MetricReporter"
#    category: "Reporters"
#    scala_dependent: true
#    versions:
#      -
#        version: "1.7.1"
#        scala_211:
#          id: 171-prometheus-211
#          url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar
#          asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.asc
#          sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.sha1
#        scala_212:
#          id: 171-prometheus-212
#          url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar
#          asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.asc
#          md1_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.sha1
#      -
#        version: "1.6.1"
#        scala_211:
#          id: 171-prometheus-211
#          url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar
#          asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.asc
#          sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.11/1.7.1/flink-metrics-prometheus_2.11-1.7.1.jar.sha1
#        scala_212:
#          id: 171-prometheus-212
#          url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar
#          asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.asc
#          md1_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-metrics-prometheus_2.12/1.7.1/flink-metrics-prometheus_2.12-1.7.1.jar.sha1

flink_releases:
  -
    version_short: "1.13"
    binary_release:
      name: "Apache Flink 1.13.0"
      scala_211:
        id: "1130-download_211"
        url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.11.tgz"
        asc_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.11.tgz.asc"
        sha512_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.11.tgz.sha512"
      scala_212:
        id: "1130-download_212"
        url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.12.tgz"
        asc_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.12.tgz.asc"
        sha512_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-bin-scala_2.12.tgz.sha512"
    source_release:
      name: "Apache Flink 1.13.0"
      id: "1130-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.13.0/flink-1.13.0-src.tgz"
      asc_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-src.tgz.asc"
      sha512_url: "https://downloads.apache.org/flink/flink-1.13.0/flink-1.13.0-src.tgz.sha512"
  -
    version_short: "1.12"
    binary_release:
      name: "Apache Flink 1.12.3"
      scala_211:
        id: "1123-download_211"
        url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.11.tgz"
        asc_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.11.tgz.asc"
        sha512_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.11.tgz.sha512"
      scala_212:
        id: "1123-download_212"
        url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.12.tgz"
        asc_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.12.tgz.asc"
        sha512_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-bin-scala_2.12.tgz.sha512"
    source_release:
      name: "Apache Flink 1.12.3"
      id: "1123-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-1.12.3/flink-1.12.3-src.tgz"
      asc_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-src.tgz.asc"
      sha512_url: "https://downloads.apache.org/flink/flink-1.12.3/flink-1.12.3-src.tgz.sha512"
    optional_components:
      -
        name: "Avro SQL Format"
        category: "SQL Formats"
        scala_dependent: false
        id: 1123-sql-format-avro
        url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-avro/1.12.3/flink-avro-1.12.3.jar
        asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-avro/1.12.3/flink-avro-1.12.3.jar.asc
        sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-avro/1.12.3/flink-avro-1.12.3.jar.sha1

flink_statefun_releases:
  -
      version_short: "3.0"
      source_release:
          name: "Apache Flink Stateful Functions 3.0.0"
          id: "300-statefun-download-source"
          flink_version: "1.12.1"
          url: "https://www.apache.org/dyn/closer.lua/flink/flink-statefun-3.0.0/flink-statefun-3.0.0-src.tgz"
          asc_url: "https://downloads.apache.org/flink/flink-statefun-3.0.0/flink-statefun-3.0.0-src.tgz.asc"
          sha512_url: "https://downloads.apache.org/flink/flink-statefun-3.0.0/flink-statefun-3.0.0-src.tgz.sha512"

component_releases:
  -
      name: "Apache Flink-shaded 13.0 Source Release"
      id: "s130-download-source"
      url: "https://www.apache.org/dyn/closer.lua/flink/flink-shaded-13.0/flink-shaded-13.0-src.tgz"
      asc_url: "https://downloads.apache.org/flink/flink-shaded-13.0/flink-shaded-13.0-src.tgz.asc"
      sha512_url: "https://downloads.apache.org/flink/flink-shaded-13.0/flink-shaded-13.0-src.tgz.sha512"
  -
      name: "Pre-bundled Hadoop 2.4.1"
      id: bundled-hadoop-241-100
      url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.4.1-10.0/flink-shaded-hadoop-2-uber-2.4.1-10.0.jar
      asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.4.1-10.0/flink-shaded-hadoop-2-uber-2.4.1-10.0.jar.asc
      sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.4.1-10.0/flink-shaded-hadoop-2-uber-2.4.1-10.0.jar.sha1
  -
      name: "Pre-bundled Hadoop 2.6.5"
      id: bundled-hadoop-265-100
      url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.6.5-10.0/flink-shaded-hadoop-2-uber-2.6.5-10.0.jar
      asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.6.5-10.0/flink-shaded-hadoop-2-uber-2.6.5-10.0.jar.asc
      sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.6.5-10.0/flink-shaded-hadoop-2-uber-2.6.5-10.0.jar.sha1
  -
      name: "Pre-bundled Hadoop 2.7.5"
      id: bundled-hadoop-275-100
      url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.7.5-10.0/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar
      asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.7.5-10.0/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar.asc
      sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.7.5-10.0/flink-shaded-hadoop-2-uber-2.7.5-10.0.jar.sha1
  -
      name: "Pre-bundled Hadoop 2.8.3"
      id: bundled-hadoop-283-100
      url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      asc_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar.asc
      sha_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar.sha1
  

release_archive:
    flink:
      -
        version_short: "1.13"
        version_long: 1.13.0
        release_date: 2021-04-30
      - 
        version_short: "1.12"
        version_long: 1.12.3
        release_date: 2021-04-29
      - 
        version_short: "1.12"
        version_long: 1.12.2
        release_date: 2021-03-03
      -
        version_short: "1.12"
        version_long: 1.12.1
        release_date: 2021-01-19
      -
        version_short: "1.12"
        version_long: 1.12.0
        release_date: 2020-12-08
      -
        version_short: "1.11"
        version_long: 1.11.3
        release_date: 2020-12-18
      -
        version_short: "1.11"
        version_long: 1.11.2
        release_date: 2020-09-17
      -
        version_short: "1.11"
        version_long: 1.11.1
        release_date: 2020-07-21
      -
        version_short: "1.11"
        version_long: 1.11.0
        release_date: 2020-07-06
      -
        version_short: "1.10"
        version_long: 1.10.3
        release_date: 2021-01-29
      -
        version_short: "1.10"
        version_long: 1.10.2
        release_date: 2020-08-25
      -
        version_short: "1.10"
        version_long: 1.10.1
        release_date: 2020-05-12
      -
        version_short: "1.10"
        version_long: 1.10.0
        release_date: 2020-02-11
      -
        version_short: 1.9
        version_long: 1.9.3
        release_date: 2020-04-24
      -
        version_short: 1.9
        version_long: 1.9.2
        release_date: 2020-01-30
      -
        version_short: 1.9
        version_long: 1.9.1
        release_date: 2019-10-18
      -
        version_short: 1.9
        version_long: 1.9.0
        release_date: 2019-08-22
      -
        version_short: 1.8
        version_long: 1.8.3
        release_date: 2019-12-11
      -
        version_short: 1.8
        version_long: 1.8.2
        release_date: 2019-09-11
      -
        version_short: 1.8
        version_long: 1.8.1
        release_date: 2019-07-02
      -
        version_short: 1.8
        version_long: 1.8.0
        release_date: 2019-04-09
      -
        version_short: 1.7
        version_long: 1.7.2
        release_date: 2019-02-15
      -
        version_short: 1.7
        version_long: 1.7.1
        release_date: 2018-12-21
      -
        version_short: 1.7
        version_long: 1.7.0
        release_date: 2018-11-30
      -
        version_short: 1.6
        version_long: 1.6.4
        release_date: 2019-02-25
      -
        version_short: 1.6
        version_long: 1.6.3
        release_date: 2018-12-22
      -
        version_short: 1.6
        version_long: 1.6.2
        release_date: 2018-10-29
      -
        version_short: 1.6
        version_long: 1.6.1
        release_date: 2018-09-19
      -
        version_short: 1.6
        version_long: 1.6.0
        release_date: 2018-08-08
      -
        version_short: 1.5
        version_long: 1.5.6
        release_date: 2018-12-21
      -
        version_short: 1.5
        version_long: 1.5.5
        release_date: 2018-10-29
      -
        version_short: 1.5
        version_long: 1.5.4
        release_date: 2018-09-19
      -
        version_short: 1.5
        version_long: 1.5.3
        release_date: 2018-08-21
      -
        version_short: 1.5
        version_long: 1.5.2
        release_date: 2018-07-31
      -
        version_short: 1.5
        version_long: 1.5.1
        release_date: 2018-07-12
      -
        version_short: 1.5
        version_long: 1.5.0
        release_date: 2018-05-25
      -
        version_short: 1.4
        version_long: 1.4.2
        release_date: 2018-03-08
      -
        version_short: 1.4
        version_long: 1.4.1
        release_date: 2018-02-15
      -
        version_short: 1.4
        version_long: 1.4.0
        release_date: 2017-11-29
      -
        version_short: 1.3
        version_long: 1.3.3
        release_date: 2018-03-15
      -
        version_short: 1.3
        version_long: 1.3.2
        release_date: 2017-08-05
      -
        version_short: 1.3
        version_long: 1.3.1
        release_date: 2017-06-23
      -
        version_short: 1.3
        version_long: 1.3.0
        release_date: 2017-06-01
      -
        version_short: 1.2
        version_long: 1.2.1
        release_date: 2017-04-26
      -
        version_short: 1.2
        version_long: 1.2.0
        release_date: 2017-02-06
      -
        version_short: 1.1
        version_long: 1.1.5
        release_date: 2017-03-22
      -
        version_short: 1.1
        version_long: 1.1.4
        release_date: 2016-12-21
      -
        version_short: 1.1
        version_long: 1.1.3
        release_date: 2016-10-13
      -
        version_short: 1.1
        version_long: 1.1.2
        release_date: 2016-09-05
      -
        version_short: 1.1
        version_long: 1.1.1
        release_date: 2016-08-11
      -
        version_short: 1.1
        version_long: 1.1.0
        release_date: 2016-08-08
      -
        version_short: 1.0
        version_long: 1.0.3
        release_date: 2016-05-12
      -
        version_short: 1.0
        version_long: 1.0.2
        release_date: 2016-04-23
      -
        version_short: 1.0
        version_long: 1.0.1
        release_date: 2016-04-06
      -
        version_short: 1.0
        version_long: 1.0.0
        release_date: 2016-03-08
      -
        version_long: 0.10.2
        release_date: 2016-02-11
      -
        version_long: 0.10.1
        release_date: 2015-11-27
      -
        version_long: 0.10.0
        release_date: 2015-11-16
      -
        version_long: 0.9.1
        release_date: 2015-09-01
      -
        version_long: 0.9.0
        release_date: 2015-06-24
      -
        version_long: 0.9.0-milestone-1
        release_date: 2015-04-13
      -
        version_long: 0.8.1
        release_date: 2015-02-20
      -
        version_long: 0.8.0
        release_date: 2015-01-22
      -
        version_long: 0.7.0-incubating
        release_date: 2014-11-04
      -
        version_long: 0.6.1-incubating
        release_date: 2014-09-26
      -
        version_long: 0.6-incubating
        release_date: 2014-08-26

    flink_statefun:
      -
        version_short: 3.0
        version_long: 3.0.0
        release_date: 2021-04-14
      -
        version_short: 2.2
        version_long: 2.2.2
        release_date: 2021-01-02
      -
        version_short: 2.2
        version_long: 2.2.1
        release_date: 2020-11-09
      -
        version_short: 2.2
        version_long: 2.2.0
        release_date: 2020-09-28
      -
        version_short: 2.1
        version_long: 2.1.0
        release_date: 2020-06-08
      -
        version_short: 2.0
        version_long: 2.0.0
        release_date: 2020-04-02

    flink_shaded:
      -
        version: 13.0
        release_date: 2021-04-06
      -
        version: 12.0
        release_date: 2020-10-09
      -
        version: 11.0
        release_date: 2020-05-29
      -
        version: 10.0
        release_date: 2020-02-17
      -
        version: 9.0
        release_date: 2019-11-23
      -
        version: 8.0
        release_date: 2019-08-28
      -
        version: 7.0
        release_date: 2019-05-30
      -
        version: 6.0
        release_date: 2019-02-12
      -
        version: 5.0
        release_date: 2018-10-15
      -
        version: 4.0
        release_date: 2018-06-06
      -
        version: 3.0
        release_date: 2018-02-28
      -
        version: 2.0
        release_date: 2017-10-30
      -
        version: 1.0
        release_date: 2017-07-27

# Version numbers used in the text for stable and snapshot versions,
# e.g. "Documentation for {{ site.stable }".
stable: "1.13"
snapshot: "1.14"

docs-stable: "https://ci.apache.org/projects/flink/flink-docs-release-1.13"
docs-snapshot: "https://ci.apache.org/projects/flink/flink-docs-master"

docs-statefun-stable: "https://ci.apache.org/projects/flink/flink-statefun-docs-release-3.0"
docs-statefun-snapshot: "https://ci.apache.org/projects/flink/flink-statefun-docs-master"

# Used by the gh_link plugin
jira: "https://issues.apache.org/jira/browse/FLINK"
stackoverflow: "https://stackoverflow.com/search?q=flink"
twitter: "https://twitter.com/apacheflink"
github: "https://github.com/apache/flink"
wiki: "https://cwiki.apache.org/confluence/display/FLINK/Apache+Flink+Home"

twitter-handle: "ApacheFlink"

#baseurl: /incubator-flink-website

#------------------------------------------------------------------------------
# BUILD CONFIG
#------------------------------------------------------------------------------
# These variables configure the jekyll build (./build_docs.sh). You don't need
# to change anything here.
#------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: plain

markdown: KramdownPygments
highlighter: pygments

# The all languages used
languages: ['en', 'zh']

kramdown:
    toc_levels: 1..3
    input: GFM
    hard_wrap: false

redcarpet:
  # https://help.github.com/articles/github-flavored-markdown
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

exclude: [README.md, docker-build.sh]

gems: ['jekyll-multiple-languages', 'jekyll-paginate']

host: 0.0.0.0

timezone: CET

# News Posts
paginate: 10
paginate_path: "blog/page:num"
